config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
resources :posts
resources :admin_users

    root to: "users#index"
  end

  resources :posts
  devise_for :users, skip: [:registrations]
  root to: 'static#homepage'
end

app/models/admin_user.rb
class AdminUser < User
end

app/models/post.rb
class Post < ActiveRecord::Base
	enum status: { submitted: 0, approved: 1, rejected: 2 }
	belongs_to :user
	validates_presence_of :date, :rationale, :overtime_request

	validates :overtime_request, numericality: { greater_than: 0.0 }

	scope :posts_by, ->(user) { where(user_id: user.id) }
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   validates_presence_of :first_name, :last_name

   def full_name
   		last_name.upcase + ", " + first_name.upcase
   	end
end

app/controllers/admin/admin_users_controller.rb
module Admin
  class AdminUsersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = AdminUser.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   AdminUser.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/application_controller.rb
module Admin
  def self.admin_types
    ['AdminUser']
    # ['AdminUser', 'SuperAdmin', 'Editor'] for multiple admin user types
  end

  class ApplicationController < Administrate::ApplicationController
    before_action :authenticate_user!
    before_filter :authenticate_admin

    def authenticate_admin
      unless Admin.admin_types.include?(current_user.try(:type))
        flash[:alert] = "You are not authorized to access this page."
        redirect_to(root_path)
      end
    end

  end
end

app/controllers/admin/posts_controller.rb
module Admin
  class PostsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Post.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Post.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = User.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   User.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    redirect_to root_path, alert: "You are not authorized to perform this action."
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :set_post, only: [:show, :edit, :update, :destroy]
	def index
		@posts = Post.posts_by current_user
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)
		@post.user_id = current_user.id

		if @post.save
			redirect_to @post, notice: 'Your post was created successfully'
		else
			render :new
		end
	end

	def edit
		authorize @post
	end

	def update
		authorize @post
		
		if @post.update(post_params)
			redirect_to @post, notice: 'Your post was edited successfully'
		else
			render :edit
		end
	end

	def show
	end

	def destroy
		@post.delete
		redirect_to posts_path, notice: 'Your post was deleted successfully'
	end

	private

		def post_params
			params.require(:post).permit(:date, :rationale, :status, :overtime_request)
		end

		def set_post
			@post = Post.find(params[:id])
		end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
def homepage
end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def active?(path)
		"active" if current_page?(path)
	end
end

app/helpers/posts_helper.rb
module PostsHelper
	def status_label status
		status_span_generator status
	end

	private

		def status_span_generator status
				case status
			when 'submitted'
				content_tag(:span, status, class: 'label label-primary')
			when 'approved'
				content_tag(:span, status, class: 'label label-success')
			when 'rejected'
				content_tag(:span, status, class: 'label label-danger')
			end
		end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Overtime</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
	<div class="row">
		<div class="col-md-12">
			<%= render 'shared/nav' %>
			<%= yield %>
		</div>
	</div>
</div>

<%= render 'shared/alerts' %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post, class: "form-horizontal" do |f| %>

	<% if @post.errors.any? %>
		<% @post.errors.full_messages.each do |error| %>
			<%= js add_gritter(error, title: "Overtime App Notification", sticky: false) %>
		<% end %>
	<% end %>

  <div class="form-group">
    <%= f.label :overtime_request, class: "col-sm-2 control-label" %>
    <%= f.text_field :overtime_request, class: "form-control" %>
  </div>


  <div class="form-group">
  	<%= f.label :date, class: "col-sm-2 control-label" %>
  	<%= f.date_field :date, class: "form-control" %>
  </div>

  <div class="form-group">
  	<%= f.label :rationale, class: "col-sm-2 control-label" %>
  	<%= f.text_area :rationale, class: "form-control" %>
  </div>

  <%= render partial: 'status', locals: { f: f } if current_user.type == 'AdminUser' %>
  
  <%= f.submit 'Save', class: 'btn btn-primary btn-block' %>

<% end %>

app/views/posts/_post.html.erb
<tr>
	<td>
		<%= post.id %>
	</td>
	<td>
		<%= post.overtime_request %>
	</td>
	<td>
		<%= post.date %>
	</td>
	<td>
		<%= post.user.full_name %>
	</td>
	<td>
		<%= link_to truncate(post.rationale), post %>
	</td>
	<td>
		<%= status_label post.status %>
	</td>
	<td>
		<%= link_to '', edit_post_path(post), id: "edit_#{post.id}", class: 'glyphicon glyphicon-pencil index-icons' if policy(post).update? %>
	</td>
	<td>
		<%= link_to '', post_path(post), method: :delete, id: "delete_post_#{post.id}_from_index", class: 'glyphicon glyphicon-trash index-icons', data: {confirm: 'Are you sure? '} %>
	</td>
</tr>

app/views/posts/_status.html.erb
<div class="form-group">
    <%= f.radio_button :status, 'submitted' %>
    <%= f.label :status, 'Submitted'%>
    
    <%= f.radio_button :status, 'approved' %>
    <%= f.label :status, 'Approved'%>
    
    <%= f.radio_button :status, 'rejected' %>
    <%= f.label :status, 'Rejected'%>
 </div>

app/views/posts/edit.html.erb
<ht>Edit</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<h1>Posts</h1>

<table class="table table-striped table-hover">
	<thead>
		<tr>
			<th>
				#
			</th>
			<th>
				Overtime Requested
			</th>
			<th>
				Date
			</th>
			<th>
				User
			</th>
			<th>
				Rationale
			</th>
			<th>
				Status
			</th>
			<th>
			</th>
			<th>
			</th>
		</tr>
	</thead>
	<tbody>
		<%= render @posts %>
	</tbody>
</table>

app/views/posts/new.html.erb
<%= form_for @post do |f| %>

  <%= f.date_field :date %>
  <%= f.text_area :rationale %>
  
  <%= f.submit 'Save' %>

<% end %>

app/views/posts/show.html.erb
<div>
	<h2><%= @post.rationale %></h2>
</div>

<div class="well">
	<div>
		<h3><span>Overtime Amount Requested:</span> <%= @post.overtime_request %></h3>
	</div>

	<div>
		<h3><span>Employee:</span> <%= @post.user.full_name %></h3>
	</div>

	<div>
		<h3><span>Date:</span> <%= @post.date %></h3>
	</div>

	<div>
		<h3><span>Current Stage of Approval:</span> <%= @post.status %></h3>
	</div>
</div>

<%= link_to 'Edit', edit_post_path(@post), class: 'btn btn-primary'  if policy(@post).update? %>

app/views/shared/_alerts.html.erb
<% if flash[:alert] %>
	<%= js add_gritter(flash[:alert], title: "Overtime App Alert", sticky: false) %>
<% elsif flash[:error] %>
	<%= js add_gritter(flash[:error], title: "Overtime App Error", sticky: false) %>
<% else %>
	<%= js add_gritter(flash[:notice], title: "Overtime App Notification", sticky: false) %>
<% end %>

app/views/shared/_nav.html.erb
<div class='logo'>
	<h1>Time Tracker</h1>
</div>
<% if current_user %>
	<ul class="custom-nav nav nav-tabs">
		<li class="<%= active?(root_path)%>">
			<%= link_to "Home", root_path %>
		</li>
		<li class="<%= active?(posts_path)%>">
			<%= link_to "Time Entries", posts_path %>
		</li>
		<li class="<%= active?(new_post_path)%>">
			<%= link_to "Add New Entry", new_post_path, id: 'new_post_from_nav' %>
		</li>
		<li class="dropdown pull-right">
			 <a href="#" data-toggle="dropdown" class="dropdown-toggle">Options<strong class="caret"></strong></a>
			<ul class="dropdown-menu">
				<% if current_user.try(:type) == 'AdminUser' %>
				<li>
					<%= link_to "Admin Dashboard", admin_root_path %>
				</li>
				<li class="divider">
				</li>
				<% end %>
				<li>
					<%= link_to "Logout", destroy_user_session_path, method: :delete %>
				</li>
			</ul>
		</li>
	</ul>
<% end %>